# permissions for end users to view pipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pipemanagercontroller
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-viewer-role
rules:
- apiGroups:
  - pipemanager.sergiotejon.github.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipemanager.sergiotejon.github.io
  resources:
  - pipelines/status
  verbs:
  - get
