apiVersion: pipemanager.sergiotejon.github.io/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipemanagercontroller
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
